### ISSUE TITLE
floatMod

### ISSUE THREAD

**Issue by Janiczek** [elm-community/basics-extra#10]
I have had a need for `(%)` for `Float`s.
It doesn't exist, so this is the next best thing:

```elm
floatMod : Float -> Float -> Float
floatMod m number =
    if number > m then
        (number - m)
            |> floatMod m
    else
        number
```

Do you think it warrants inclusion?

EDIT: the argument order makes it easy to pipeline:
```elm
135.5
    |> floatMod 20.5
--> 12.5
```

**Comment by jvoigtlaender** [comment]
You seen the (very old) discussion of this at https://github.com/elm-lang/core/issues/4? Also, it‘s part of a collection of open proposals: https://github.com/elm-lang/core/issues/721

That’s not to say it doesn’t make sense to add to the extra library here. 

But I‘m concerned about the order of arguments. Pipelining is nice, but not always called for. Specifically for math operations I‘m not certain pipelining is very common. We don’t have a „pipelined“ minus, for example. And the fact that the type of the function does not help with knowing which argument is which makes it a bit dangerous. 

The functions proposed in the discussions linked to above also all use the other order. Maybe that’s because pipelining was not so popular yet back then?

**Comment by jvoigtlaender** [comment]
The implementation shouldn‘t use repeated subtraction, I think. More efficient implementations are in the discussions linked above.

**Comment by Janiczek** [comment]
Ah, I haven't seen the discussions in other repos. Thank you for the links!

Well, until it's in core, I think it would make sense to have it here.

Re the more efficient implementation - I'm all for it!

Re argument order - if it was an operator, there would be no doubt (`num % m`), but does that reasoning change when it's not an operator? `fmod num m`... (We can add operators now but will not be able to in 0.19)

In any case, I'm happy for it to added in any argument order :)

**Comment by jvoigtlaender** [comment]
I've added and released a version of/with this function: http://package.elm-lang.org/packages/elm-community/basics-extra/2.3.0/Basics-Extra#fmod

The documentation is very rudimentary. I'd welcome a pull request adding some more words and possibly examples there. That would then be released as a patch version.

**Comment by Janiczek** [comment]
Thank you! I should be able to add a PR with some documentation and examples tomorrow.

A question: is there a reason the divisor is limited to `Int`?

**Comment by jvoigtlaender** [comment]
Good point. I'll change that to take a `Float` as divisor as well. Due to the type change, that will require a major version bump. But that's just fine, since the other currently open pull request in this repo, https://github.com/elm-community/basics-extra/pull/6, has been waiting for a long time to finally be part of a major version release (since `elm-package` would not detect it as a major version change on its own). :smile:

**Comment by jvoigtlaender** [comment]
Now published as http://package.elm-lang.org/packages/elm-community/basics-extra/3.0.0/Basics-Extra#fmod

A pull request with a bit more elaborated documentation for this function is still very much welcome. That would then become version 3.0.1 of the package.
